name: Update IT Jobs

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your default branch
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install 'requests' and 'bs4' modules
      run: pip install requests beautifulsoup4

    - name: Run scrape.py
      run: |
        python scrape-it.py
        git config --global user.email "you@example.com"
        git config --global user.name "researchersec [bot]"

        ADDED_FILES=$(git diff --name-only)
        DELETED_FILES=$(git diff --name-only --diff-filter=D)

        if [ -n "$ADDED_FILES" ]; then
          git add .
          git commit -m "Auto scrape and add/update files: $ADDED_FILES"
        elif [ -n "$DELETED_FILES" ]; then
          git add .
          git commit -m "Auto scrape and delete files: $DELETED_FILES"
        else
          echo "No changes found."
        fi

        git push
